#!/bin/sh
#
# StratoSwarm Swarmlet Container Entrypoint
# Handles environment-based configuration and automatic cluster joining
#

set -e

# Colors for output (compatible with sh)
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Print functions
print_status() {
    echo -e "${GREEN}[INFO]${NC} $1" >&2
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1" >&2
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

print_debug() {
    if [ "$SWARMLET_DEBUG" = "true" ]; then
        echo -e "${BLUE}[DEBUG]${NC} $1" >&2
    fi
}

# Default values
DEFAULT_DATA_DIR="/data"
DEFAULT_CONFIG_FILE="/config/config.toml"
DEFAULT_API_PORT="8080"
DEFAULT_METRICS_PORT="9090"

# Environment variables with defaults
DATA_DIR="${SWARMLET_DATA_DIR:-$DEFAULT_DATA_DIR}"
CONFIG_FILE="${SWARMLET_CONFIG_FILE:-$DEFAULT_CONFIG_FILE}"
AUTO_JOIN="${SWARMLET_AUTO_JOIN:-true}"
COMMAND_EXEC="${SWARMLET_COMMAND_EXEC:-disabled}"
LOG_LEVEL="${SWARMLET_LOG_LEVEL:-info}"
API_PORT="${SWARMLET_API_PORT:-$DEFAULT_API_PORT}"
METRICS_PORT="${SWARMLET_METRICS_PORT:-$DEFAULT_METRICS_PORT}"

# Function to check if running in container
is_container() {
    [ -f /.dockerenv ] || [ -n "$container" ]
}

# Function to check required environment variables
check_required_env() {
    print_status "Checking required environment variables..."
    
    missing_vars=""
    
    if [ -z "$SWARMLET_CLUSTER_TOKEN" ]; then
        missing_vars="$missing_vars SWARMLET_CLUSTER_TOKEN"
    fi
    
    if [ -z "$SWARMLET_CLUSTER_HOST" ]; then
        missing_vars="$missing_vars SWARMLET_CLUSTER_HOST"
    fi
    
    if [ -n "$missing_vars" ]; then
        print_error "Required environment variables are missing:$missing_vars"
        print_error "Please set these variables and restart the container."
        print_error ""
        print_error "Example:"
        print_error "  docker run -e SWARMLET_CLUSTER_TOKEN=your_token \\"
        print_error "             -e SWARMLET_CLUSTER_HOST=cluster.local:7946 \\"
        print_error "             stratoswarm/swarmlet:latest"
        exit 1
    fi
    
    print_status "Required environment variables found ✓"
}

# Function to create directories
ensure_directories() {
    print_status "Ensuring required directories exist..."
    
    # Create data directory if it doesn't exist
    if [ ! -d "$DATA_DIR" ]; then
        print_debug "Creating data directory: $DATA_DIR"
        mkdir -p "$DATA_DIR" || {
            print_error "Failed to create data directory: $DATA_DIR"
            exit 1
        }
    fi
    
    # Create config directory if it doesn't exist
    config_dir=$(dirname "$CONFIG_FILE")
    if [ ! -d "$config_dir" ]; then
        print_debug "Creating config directory: $config_dir"
        mkdir -p "$config_dir" || {
            print_error "Failed to create config directory: $config_dir"
            exit 1
        }
    fi
    
    # Create logs directory
    if [ ! -d "$DATA_DIR/logs" ]; then
        mkdir -p "$DATA_DIR/logs"
    fi
    
    print_status "Directories ensured ✓"
}

# Function to generate configuration file
generate_config() {
    print_status "Generating configuration file..."
    
    # Skip if config file already exists and not in force mode
    if [ -f "$CONFIG_FILE" ] && [ "$SWARMLET_FORCE_CONFIG" != "true" ]; then
        print_status "Configuration file exists, skipping generation"
        print_status "Set SWARMLET_FORCE_CONFIG=true to regenerate"
        return 0
    fi
    
    # Get node name (default to hostname)
    node_name="${SWARMLET_NODE_NAME:-$(hostname)}"
    
    # Generate the configuration
    cat > "$CONFIG_FILE" << EOF
# StratoSwarm Swarmlet Configuration
# Auto-generated by container entrypoint
# Generated at: $(date -Iseconds)

[node]
name = "$node_name"
data_dir = "$DATA_DIR"

[network]  
listen = "0.0.0.0:$API_PORT"
discovery = ["mdns", "broadcast"]

[mesh]
join_token = "$SWARMLET_CLUSTER_TOKEN"
coordinator = "$SWARMLET_CLUSTER_HOST"

[capabilities]
advertise = [
    "workload_execution",
    "health_reporting",
    "metrics_collection"
]

[workloads]
accept = ["container", "process"]
max_workloads = ${SWARMLET_MAX_WORKLOADS:-10}

[monitoring]
metrics_enabled = true
metrics_port = $METRICS_PORT
health_check_interval = "${SWARMLET_HEALTH_INTERVAL:-30s}"

[logging]
level = "$LOG_LEVEL"
file = "$DATA_DIR/logs/swarmlet.log"
max_size = ${SWARMLET_LOG_MAX_SIZE:-100}
max_files = ${SWARMLET_LOG_MAX_FILES:-5}
EOF

    # Add command execution capabilities if enabled
    if [ "$COMMAND_EXEC" = "enabled" ] || [ "$COMMAND_EXEC" = "true" ]; then
        cat >> "$CONFIG_FILE" << EOF

[command_execution]
enabled = true
timeout_seconds = ${SWARMLET_COMMAND_TIMEOUT:-300}
EOF
        # Add allowed commands if specified
        if [ -n "$SWARMLET_ALLOWED_COMMANDS" ]; then
            echo "allowed_commands = [$(echo "$SWARMLET_ALLOWED_COMMANDS" | sed 's/,/", "/g' | sed 's/^/"/; s/$/"/' )]" >> "$CONFIG_FILE"
        fi
        
        # Add command execution to capabilities
        sed -i 's/\(advertise = \[\)/\1\n    "command_execution",/' "$CONFIG_FILE"
        sed -i 's/\(accept = \[.*\)\]/\1, "shell"]/' "$CONFIG_FILE"
    fi
    
    # Add resource limits if specified
    if [ -n "$SWARMLET_MEMORY_LIMIT" ] || [ -n "$SWARMLET_CPU_LIMIT" ]; then
        cat >> "$CONFIG_FILE" << EOF

[limits]
EOF
        if [ -n "$SWARMLET_MEMORY_LIMIT" ]; then
            echo "memory_gb = $SWARMLET_MEMORY_LIMIT" >> "$CONFIG_FILE"
        fi
        if [ -n "$SWARMLET_CPU_LIMIT" ]; then
            echo "cpu_cores = $SWARMLET_CPU_LIMIT" >> "$CONFIG_FILE"
        fi
    fi
    
    print_status "Configuration generated: $CONFIG_FILE ✓"
}

# Function to validate configuration
validate_config() {
    print_status "Validating configuration..."
    
    # Check if swarmlet binary exists
    if ! command -v /swarmlet >/dev/null 2>&1; then
        print_error "Swarmlet binary not found at /swarmlet"
        exit 1
    fi
    
    # Test configuration file syntax (if supported)
    # This would depend on the swarmlet binary having a config validation option
    
    print_status "Configuration validation passed ✓"
}

# Function to show startup information
show_startup_info() {
    print_status "StratoSwarm Swarmlet starting..."
    print_status "Node Name: ${SWARMLET_NODE_NAME:-$(hostname)}"
    print_status "Cluster Host: $SWARMLET_CLUSTER_HOST"
    print_status "Auto Join: $AUTO_JOIN"
    print_status "Command Execution: $COMMAND_EXEC"
    print_status "Log Level: $LOG_LEVEL"
    print_status "Data Directory: $DATA_DIR"
    print_status "Config File: $CONFIG_FILE"
    
    if [ "$SWARMLET_DEBUG" = "true" ]; then
        print_debug "Environment variables:"
        env | grep "SWARMLET_" | sort
    fi
}

# Function to handle signals for graceful shutdown
setup_signal_handlers() {
    # Handle SIGTERM for graceful shutdown
    trap 'print_status "Received SIGTERM, shutting down gracefully..."; kill $PID; wait $PID' TERM
    trap 'print_status "Received SIGINT, shutting down gracefully..."; kill $PID; wait $PID' INT
}

# Function to wait for cluster connectivity
wait_for_cluster() {
    if [ "$SWARMLET_WAIT_FOR_CLUSTER" = "true" ]; then
        print_status "Checking cluster connectivity..."
        
        cluster_host=$(echo "$SWARMLET_CLUSTER_HOST" | cut -d: -f1)
        cluster_port=$(echo "$SWARMLET_CLUSTER_HOST" | cut -d: -f2)
        
        max_wait=${SWARMLET_CLUSTER_WAIT_TIMEOUT:-60}
        wait_time=0
        
        while [ $wait_time -lt $max_wait ]; do
            if nc -z "$cluster_host" "$cluster_port" 2>/dev/null; then
                print_status "Cluster is reachable ✓"
                break
            fi
            
            print_debug "Waiting for cluster connectivity... ($wait_time/$max_wait)"
            sleep 2
            wait_time=$((wait_time + 2))
        done
        
        if [ $wait_time -ge $max_wait ]; then
            print_warning "Cluster connectivity timeout, continuing anyway..."
        fi
    fi
}

# Function to perform health check
health_check() {
    if command -v /swarmlet >/dev/null 2>&1; then
        /swarmlet profile-hardware >/dev/null 2>&1
    else
        # Fallback health check
        [ -f "$CONFIG_FILE" ] && [ -d "$DATA_DIR" ]
    fi
}

# Function to run pre-start hooks
run_pre_start_hooks() {
    if [ -n "$SWARMLET_PRE_START_SCRIPT" ] && [ -f "$SWARMLET_PRE_START_SCRIPT" ]; then
        print_status "Running pre-start hook: $SWARMLET_PRE_START_SCRIPT"
        chmod +x "$SWARMLET_PRE_START_SCRIPT"
        "$SWARMLET_PRE_START_SCRIPT" || {
            print_error "Pre-start hook failed"
            exit 1
        }
    fi
}

# Main function
main() {
    print_status "=== StratoSwarm Swarmlet Container Entrypoint ==="
    
    # Show container information
    if is_container; then
        print_debug "Running in container environment"
    fi
    
    # Check if we're being asked to run a specific command
    if [ $# -gt 0 ]; then
        case "$1" in
            "daemon"|"join"|"discover"|"profile-hardware"|"test-connection")
                # These are valid swarmlet commands, continue with setup
                ;;
            "sh"|"bash"|"/bin/sh"|"/bin/bash")
                # Shell access requested, skip setup
                print_status "Shell access requested, skipping swarmlet setup"
                exec "$@"
                ;;
            "help"|"--help"|"-h")
                exec /swarmlet --help
                ;;
            "version"|"--version"|"-v")
                exec /swarmlet --version
                ;;
            *)
                # Unknown command, let swarmlet handle it
                print_debug "Passing through command: $*"
                ;;
        esac
    fi
    
    # Only perform setup if we're running swarmlet commands
    if [ $# -eq 0 ] || [ "$1" = "daemon" ] || [ "$AUTO_JOIN" = "true" ]; then
        # Check required environment variables
        check_required_env
        
        # Ensure directories exist
        ensure_directories
        
        # Generate configuration
        generate_config
        
        # Validate configuration
        validate_config
        
        # Show startup information
        show_startup_info
        
        # Run pre-start hooks
        run_pre_start_hooks
        
        # Wait for cluster if requested
        wait_for_cluster
        
        # Setup signal handlers for graceful shutdown
        setup_signal_handlers
    fi
    
    # Determine what to run
    if [ $# -eq 0 ]; then
        # No arguments provided, run daemon mode
        if [ "$AUTO_JOIN" = "true" ]; then
            print_status "Starting in auto-join daemon mode..."
            set -- "join" "--token" "$SWARMLET_CLUSTER_TOKEN" \
                   "--cluster" "$SWARMLET_CLUSTER_HOST" \
                   "--data-dir" "$DATA_DIR"
            
            if [ -n "$SWARMLET_NODE_NAME" ]; then
                set -- "$@" "--name" "$SWARMLET_NODE_NAME"
            fi
        else
            print_status "Starting in daemon mode..."
            set -- "daemon" "-c" "$CONFIG_FILE"
        fi
    fi
    
    # Start swarmlet with the determined arguments
    print_status "Executing: /swarmlet $*"
    exec /swarmlet "$@" &
    PID=$!
    
    # Wait for the process
    wait $PID
}

# Handle the case where the script is sourced vs executed
if [ "${0##*/}" = "swarmlet-entrypoint.sh" ]; then
    main "$@"
fi