#!/bin/bash
#
# StratoSwarm Node Bootstrap Script
# Auto-generated by cluster coordinator
#
# Generated: {{GENERATED_AT}}
# Token expires: {{TOKEN_EXPIRY}}
#
# Usage:
#   curl -sSL "https://coordinator.stratoswarm.com/api/v1/install?token=TOKEN" | bash
#

set -euo pipefail

# ============================================================================
# EMBEDDED CONFIGURATION (Injected by coordinator)
# ============================================================================
CLUSTER_HOST="{{CLUSTER_HOST}}"
CLUSTER_PORT="{{CLUSTER_PORT}}"
CLUSTER_TOKEN="{{CLUSTER_TOKEN}}"
SWARMLET_VERSION="{{SWARMLET_VERSION}}"
DOCKER_IMAGE="{{DOCKER_IMAGE}}"
BINARY_CHECKSUM_LINUX_AMD64="{{CHECKSUM_LINUX_AMD64}}"
BINARY_CHECKSUM_LINUX_ARM64="{{CHECKSUM_LINUX_ARM64}}"
BINARY_CHECKSUM_DARWIN_AMD64="{{CHECKSUM_DARWIN_AMD64}}"
BINARY_CHECKSUM_DARWIN_ARM64="{{CHECKSUM_DARWIN_ARM64}}"
RELEASES_BASE_URL="{{RELEASES_BASE_URL}}"

# ============================================================================
# SCRIPT CONFIGURATION
# ============================================================================
SCRIPT_VERSION="1.0.0"
INSTALL_DIR="/usr/local/bin"
CONFIG_DIR="/etc/swarmlet"
DATA_DIR="/var/lib/swarmlet"
LOG_DIR="/var/log/swarmlet"
CONTAINER_NAME="stratoswarm-swarmlet"
SERVICE_NAME="swarmlet"

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly CYAN='\033[0;36m'
readonly NC='\033[0m'

# ============================================================================
# HELPER FUNCTIONS
# ============================================================================

print_banner() {
    echo -e "${CYAN}"
    echo "  _____ _             _        _____                             "
    echo " / ____| |           | |      / ____|                            "
    echo "| (___ | |_ _ __ __ _| |_ ___| (_____      ____ _ _ __ _ __ ___  "
    echo " \\___ \\| __| '__/ _\` | __/ _ \\\\___ \\ \\ /\\ / / _\` | '__| '_ \` _ \\ "
    echo " ____) | |_| | | (_| | || (_) |___) \\ V  V / (_| | |  | | | | | |"
    echo "|_____/ \\__|_|  \\__,_|\\__\\___/_____/ \\_/\\_/ \\__,_|_|  |_| |_| |_|"
    echo -e "${NC}"
    echo "Node Bootstrap Script v${SCRIPT_VERSION}"
    echo "Cluster: ${CLUSTER_HOST}:${CLUSTER_PORT}"
    echo ""
}

print_status() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

print_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

print_step() {
    echo -e "${BLUE}[STEP]${NC} $1"
}

print_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

# ============================================================================
# ENVIRONMENT DETECTION
# ============================================================================

detect_os() {
    case "$(uname -s)" in
        Linux*)  echo "linux";;
        Darwin*) echo "darwin";;
        *)       echo "unknown";;
    esac
}

detect_arch() {
    case "$(uname -m)" in
        x86_64|amd64)  echo "amd64";;
        aarch64|arm64) echo "arm64";;
        *)             echo "unknown";;
    esac
}

detect_init_system() {
    if [[ -d /run/systemd/system ]]; then
        echo "systemd"
    elif command -v launchctl &>/dev/null; then
        echo "launchd"
    else
        echo "unknown"
    fi
}

has_docker() {
    if command -v docker &>/dev/null && docker info &>/dev/null 2>&1; then
        return 0
    fi
    return 1
}

get_expected_checksum() {
    local os="$1"
    local arch="$2"

    case "${os}_${arch}" in
        linux_amd64)  echo "$BINARY_CHECKSUM_LINUX_AMD64";;
        linux_arm64)  echo "$BINARY_CHECKSUM_LINUX_ARM64";;
        darwin_amd64) echo "$BINARY_CHECKSUM_DARWIN_AMD64";;
        darwin_arm64) echo "$BINARY_CHECKSUM_DARWIN_ARM64";;
        *)            echo "";;
    esac
}

# ============================================================================
# REQUIREMENT CHECKS
# ============================================================================

check_requirements() {
    print_step "Checking system requirements..."

    local os=$(detect_os)
    local arch=$(detect_arch)

    if [[ "$os" == "unknown" ]]; then
        print_error "Unsupported operating system: $(uname -s)"
        exit 1
    fi

    if [[ "$arch" == "unknown" ]]; then
        print_error "Unsupported architecture: $(uname -m)"
        exit 1
    fi

    # Check for curl or wget
    if ! command -v curl &>/dev/null && ! command -v wget &>/dev/null; then
        print_error "Neither curl nor wget found. Please install one of them."
        exit 1
    fi

    # Check for root/sudo for system directories
    if [[ $EUID -ne 0 ]]; then
        if ! command -v sudo &>/dev/null; then
            print_error "This script requires root privileges. Please run with sudo."
            exit 1
        fi
        SUDO="sudo"
    else
        SUDO=""
    fi

    print_status "OS: $os, Arch: $arch"
    print_status "Requirements check passed"
}

# ============================================================================
# DOCKER INSTALLATION
# ============================================================================

install_via_docker() {
    print_step "Installing via Docker..."

    # Check if container already exists
    if docker ps -a --format '{{.Names}}' | grep -q "^${CONTAINER_NAME}$"; then
        print_warning "Container '${CONTAINER_NAME}' already exists"
        read -p "Remove existing container? [y/N]: " -n 1 -r
        echo
        if [[ $REPLY =~ ^[Yy]$ ]]; then
            docker stop "$CONTAINER_NAME" 2>/dev/null || true
            docker rm "$CONTAINER_NAME" 2>/dev/null || true
        else
            print_error "Cannot proceed with existing container"
            exit 1
        fi
    fi

    # Pull the image
    print_status "Pulling Docker image: ${DOCKER_IMAGE}:${SWARMLET_VERSION}..."
    docker pull "${DOCKER_IMAGE}:${SWARMLET_VERSION}"

    # Create necessary directories
    $SUDO mkdir -p "$DATA_DIR" "$CONFIG_DIR"

    # Generate config file
    generate_config

    # Run the container
    print_status "Starting swarmlet container..."
    docker run -d \
        --name "$CONTAINER_NAME" \
        --restart unless-stopped \
        --network host \
        -v "${CONFIG_DIR}:/etc/swarmlet:ro" \
        -v "${DATA_DIR}:/var/lib/swarmlet" \
        -e "CLUSTER_HOST=${CLUSTER_HOST}" \
        -e "CLUSTER_PORT=${CLUSTER_PORT}" \
        -e "CLUSTER_TOKEN=${CLUSTER_TOKEN}" \
        -e "SWARMLET_AUTO_JOIN=true" \
        "${DOCKER_IMAGE}:${SWARMLET_VERSION}"

    print_success "Docker container started successfully"
}

# ============================================================================
# BINARY INSTALLATION
# ============================================================================

install_via_binary() {
    print_step "Installing via native binary..."

    local os=$(detect_os)
    local arch=$(detect_arch)
    local binary_url="${RELEASES_BASE_URL}/${SWARMLET_VERSION}/${os}-${arch}/swarmlet"
    local expected_checksum=$(get_expected_checksum "$os" "$arch")

    if [[ -z "$expected_checksum" ]]; then
        print_error "No binary available for ${os}/${arch}"
        exit 1
    fi

    # Download binary
    print_status "Downloading swarmlet binary..."
    local temp_file=$(mktemp)

    if command -v curl &>/dev/null; then
        curl -fsSL "$binary_url" -o "$temp_file"
    else
        wget -q "$binary_url" -O "$temp_file"
    fi

    # Verify checksum
    print_status "Verifying checksum..."
    local actual_checksum
    if command -v sha256sum &>/dev/null; then
        actual_checksum=$(sha256sum "$temp_file" | cut -d' ' -f1)
    elif command -v shasum &>/dev/null; then
        actual_checksum=$(shasum -a 256 "$temp_file" | cut -d' ' -f1)
    else
        print_warning "No sha256 tool found, skipping checksum verification"
        actual_checksum="$expected_checksum"
    fi

    if [[ "$actual_checksum" != "$expected_checksum" ]]; then
        print_error "Checksum mismatch!"
        print_error "Expected: $expected_checksum"
        print_error "Got:      $actual_checksum"
        rm -f "$temp_file"
        exit 1
    fi

    # Install binary
    print_status "Installing binary to ${INSTALL_DIR}/swarmlet..."
    $SUDO install -m 755 "$temp_file" "${INSTALL_DIR}/swarmlet"
    rm -f "$temp_file"

    # Create directories
    $SUDO mkdir -p "$DATA_DIR" "$CONFIG_DIR" "$LOG_DIR"

    # Generate config
    generate_config

    # Install service
    install_service

    print_success "Binary installation complete"
}

# ============================================================================
# SERVICE INSTALLATION
# ============================================================================

install_service() {
    local init_system=$(detect_init_system)

    case "$init_system" in
        systemd)
            install_systemd_service
            ;;
        launchd)
            install_launchd_service
            ;;
        *)
            print_warning "Unknown init system. Service not installed."
            print_warning "You'll need to start swarmlet manually."
            ;;
    esac
}

install_systemd_service() {
    print_status "Installing systemd service..."

    $SUDO tee /etc/systemd/system/${SERVICE_NAME}.service > /dev/null << EOF
[Unit]
Description=StratoSwarm Swarmlet Agent
Documentation=https://docs.stratoswarm.com
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=${INSTALL_DIR}/swarmlet --config ${CONFIG_DIR}/config.toml
Restart=always
RestartSec=5
StandardOutput=journal
StandardError=journal
User=root

[Install]
WantedBy=multi-user.target
EOF

    $SUDO systemctl daemon-reload
    $SUDO systemctl enable ${SERVICE_NAME}
    $SUDO systemctl start ${SERVICE_NAME}

    print_status "Systemd service installed and started"
}

install_launchd_service() {
    print_status "Installing launchd service..."

    local plist_path="/Library/LaunchDaemons/io.stratoswarm.swarmlet.plist"

    $SUDO tee "$plist_path" > /dev/null << EOF
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>io.stratoswarm.swarmlet</string>
    <key>ProgramArguments</key>
    <array>
        <string>${INSTALL_DIR}/swarmlet</string>
        <string>--config</string>
        <string>${CONFIG_DIR}/config.toml</string>
    </array>
    <key>RunAtLoad</key>
    <true/>
    <key>KeepAlive</key>
    <true/>
    <key>StandardOutPath</key>
    <string>${LOG_DIR}/swarmlet.log</string>
    <key>StandardErrorPath</key>
    <string>${LOG_DIR}/swarmlet.error.log</string>
</dict>
</plist>
EOF

    $SUDO launchctl load "$plist_path"

    print_status "Launchd service installed and started"
}

# ============================================================================
# CONFIGURATION
# ============================================================================

generate_config() {
    print_status "Generating configuration..."

    local node_name=$(hostname)

    $SUDO tee "${CONFIG_DIR}/config.toml" > /dev/null << EOF
# StratoSwarm Swarmlet Configuration
# Auto-generated by bootstrap script

[cluster]
host = "${CLUSTER_HOST}"
port = ${CLUSTER_PORT}
token = "${CLUSTER_TOKEN}"

[node]
name = "${node_name}"
data_dir = "${DATA_DIR}"

[api]
port = 8080
metrics_port = 9090

[heartbeat]
interval_secs = 30

[auto_join]
enabled = true
EOF

    print_status "Configuration written to ${CONFIG_DIR}/config.toml"
}

# ============================================================================
# VERIFICATION
# ============================================================================

verify_installation() {
    print_step "Verifying installation..."

    local max_attempts=30
    local attempt=0
    local health_url="http://127.0.0.1:8080/health"

    print_status "Waiting for swarmlet to become healthy..."

    while [[ $attempt -lt $max_attempts ]]; do
        if curl -sf "$health_url" > /dev/null 2>&1; then
            print_success "Swarmlet is healthy!"
            return 0
        fi
        sleep 1
        ((attempt++))
        echo -n "."
    done

    echo
    print_warning "Swarmlet did not become healthy within ${max_attempts} seconds"
    print_warning "Check logs for more information"
    return 1
}

# ============================================================================
# CLEANUP
# ============================================================================

cleanup() {
    # Cleanup function for error handling
    if [[ $? -ne 0 ]]; then
        print_error "Installation failed. Cleaning up..."
    fi
}

trap cleanup EXIT

# ============================================================================
# MAIN
# ============================================================================

main() {
    print_banner

    # Validate embedded configuration
    if [[ "$CLUSTER_TOKEN" == "{{CLUSTER_TOKEN}}" ]]; then
        print_error "This script contains placeholder values."
        print_error "It should be generated by the cluster coordinator."
        exit 1
    fi

    check_requirements

    # Auto-detect installation method
    print_step "Detecting installation method..."

    if has_docker; then
        print_status "Docker detected - using container deployment"
        install_via_docker
    else
        print_status "Docker not available - using native binary"
        install_via_binary
    fi

    # Verify installation
    if verify_installation; then
        echo
        print_success "StratoSwarm node installation complete!"
        print_status "Node is now connected to cluster at ${CLUSTER_HOST}:${CLUSTER_PORT}"
        echo
        print_status "Useful commands:"

        if has_docker; then
            echo "  View logs:    docker logs -f ${CONTAINER_NAME}"
            echo "  Stop node:    docker stop ${CONTAINER_NAME}"
            echo "  Start node:   docker start ${CONTAINER_NAME}"
        else
            local init_system=$(detect_init_system)
            if [[ "$init_system" == "systemd" ]]; then
                echo "  View logs:    journalctl -u ${SERVICE_NAME} -f"
                echo "  Stop node:    sudo systemctl stop ${SERVICE_NAME}"
                echo "  Start node:   sudo systemctl start ${SERVICE_NAME}"
            elif [[ "$init_system" == "launchd" ]]; then
                echo "  View logs:    tail -f ${LOG_DIR}/swarmlet.log"
                echo "  Stop node:    sudo launchctl unload /Library/LaunchDaemons/io.stratoswarm.swarmlet.plist"
            fi
        fi
        echo
    else
        print_warning "Installation completed but health check failed"
        print_warning "The node may still join the cluster after startup"
    fi
}

main "$@"
